### ISSUE TITLE
Integrate with docker-compose

### ISSUE THREAD

**Issue by apirobot** [christophetd/docker-python-sandbox#18]
I have two services inside docker-compose file that setting up my web application:

```yml
services:

  django:
    ...

  postgres:
    ...
```

Can I somehow add this sandbox as a third service? I was thinking about docker inside docker, but I'm not sure it's correct. Also, I don't know how to do it properly. Did anyone struggle with such a problem?
